#!/bin/bash

set -e

heroku container:login

APP=$(heroku apps:info --json | jq -r '.app.name')

read -p "Ready to deploy ${APP} to heroku? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	heroku container:push web $(cat .env | grep -v "#" | xargs printf -- '--arg %s\n' | xargs)
	heroku container:release web

	WEB_URL=$(heroku apps:info --json | jq -r '.app.web_url')
	open $WEB_URL
fi
